#include "${CMAKE_CURRENT_LIST_DIR}/ArcFileNames.h"

#define SYNTH_ORIGARC_FILEPATH "${SYNTH_ARC_TRAINING_PATH}"
#define SYNTH_ARCPRIZE_PATH "${SYNTH_ARC_PRIZE_PATH}"
#define SYNTH_TTF_FONT_PATH "${SYNTH_TTF_FONT_PATH}"
